#!/opt/local/bin/perl

# Project Euler Problem #29
#
# Consider all integer combinations of a^(b) for 2 ² a ² 5 and 2 ² b ² 5:
# 
#     2^(2)=4, 2^(3)=8, 2^(4)=16, 2^(5)=32
#     3^(2)=9, 3^(3)=27, 3^(4)=81, 3^(5)=243
#     4^(2)=16, 4^(3)=64, 4^(4)=256, 4^(5)=1024
#     5^(2)=25, 5^(3)=125, 5^(4)=625, 5^(5)=3125
# 
# If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:
# 
# 4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125
# 
# How many distinct terms are in the sequence generated by a^(b) for 2 ² a ² 100 and 2 ² b ² 100?
# 


use strict;
use warnings;
use bignum (p => 2000);

require "/Users/don/bin/scripts/euler/functions.pm";

# Disable output buffering
select((select(STDOUT), $|=1)[0]);

print "Timing started....\n\n";
startTiming();

my $result = 0;
my $lower_limit = 2;
my $upper_limit = 100;
my %NUMS;

my @values = ();

for (my $a = $lower_limit; $a <= $upper_limit; $a++) {
  for (my $b = $lower_limit; $b <= $upper_limit; $b++) {
    $result = $a ** $b;
    if (defined $NUMS{$result}) {
      $NUMS{$result}++;
    } else {
      push @values, $result;
      $NUMS{$result} = 1;
    }
  }
  
  print "$a\n";
}


print "\n\nAnswer: " . (scalar(@values)) . "\n\n";

print "\n\n" . endTiming() . " second(s) elapsed.\n\n";


# Answer: 9183